# Generated by Django 5.2.10 on 2026-01-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('Published_date', models.DateField()),
                ('Author', models.CharField(max_length=50)),
                ('ISBN', models.IntegerField()),
                ('Stock', models.IntegerField()),
            ],
        ),
    ]
