# Generated by Django 5.2.10 on 2026-01-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
