# Generated by Django 5.2.10 on 2026-01-13 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('reader', '0002_alter_bookreader_due_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookReader',
            new_name='Bookborrowed',
        ),
    ]
