# Generated by Django 5.2.10 on 2026-01-14 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_stock'),
        ('reader', '0003_rename_bookreader_bookborrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrowed',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookborrowed',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_records', to='books.books'),
        ),
    ]
